dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-undertow'
    implementation project(':usecase')
    implementation project(':model')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'io.micrometer:micrometer-registry-prometheus'
    //implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server'
    //implementation 'org.springframework.boot:spring-boot-starter-security'

    // Apache POI para manejar archivos Excel (XLSX)
    implementation 'org.apache.poi:poi-ooxml:5.2.3'
    implementation 'com.opencsv:opencsv:5.7.1'

    // Si también necesitas soporte para formatos más antiguos (XLS)
    implementation 'org.apache.poi:poi:5.2.3'

    // Requiere el paquete de XML Beans para trabajar con el formato ooxml
    implementation 'org.apache.xmlbeans:xmlbeans:5.1.1'

    compileOnly group: 'javax.servlet', name: 'javax.servlet-api', version: '3.0.1'
}


configurations{
	implementation.exclude group: 'org.springframework.boot', module: 'spring-boot-starter-tomcat'
}