apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-database-analysis-deployment
  namespace: parking
  labels:
    app: ms-database-analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-database-analysis
  template:
    metadata:
      labels:
        app: ms-database-analysis
    spec:
      containers:
        - name: ms-database-analysis
          image: 593793033424.dkr.ecr.us-east-1.amazonaws.com/parking/back:ms-database-analisis_v2
          resources:
            requests:
              cpu: "900m"      # 100 millicores (0.1 CPU)
              memory: "410Mi"  # 128 Megabytes de RAM
            limits:
              cpu: "1800m"      # 500 millicores (0.5 CPU)
              memory: "1224Mi"  # 512 Megabytes de RAM
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "local"
