# Imagen oficial de Bun
FROM oven/bun:1

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiamos package.json y lock primero (mejor cache de Docker)
COPY package.json bun.lockb* ./

# Instalamos dependencias
RUN bun install

# Copiamos el resto del proyecto
COPY . .

# Build de Astro
RUN bun run build

# Puerto que usará Astro
EXPOSE 4321

# Comando para correr el servidor
CMD ["bun", "run", "preview", "--host", "0.0.0.0", "--port", "4321"]