version: '3.8'

services:
  # ==========================================
  # FRONTEND 
  # ==========================================

  # 1. Landing Page Principal
  front-savia-check:
    build:
      context: ../front/project-a  # <--- Apuntamos directo a la carpeta del proyecto
      dockerfile: ../dockerfile     # <--- El dockerfile está un nivel arriba
    container_name: savia_front_check
    restart: always
    networks:
      - savia_proxy
      - savia_internal
    labels:
      - "traefik.enable=true"
      
      # --- ROUTER PARA HTTP (Puerto 81) ---
      - "traefik.http.routers.savia-landing.rule=Host(`check.saviaservicios.com`)"
      - "traefik.http.routers.savia-landing.entrypoints=web"
      - "traefik.http.routers.savia-landing.priority=10"
      # OJO: NO poner .tls=true aquí para que el 81 sea HTTP plano

      # --- ROUTER PARA HTTPS (Puerto 8080) ---
      - "traefik.http.routers.savia-landing-secure.rule=Host(`check.saviaservicios.com`)"
      - "traefik.http.routers.savia-landing-secure.entrypoints=websecure"
      - "traefik.http.routers.savia-landing-secure.priority=11"
      - "traefik.http.routers.savia-landing-secure.tls=true" # Solo para el 8080

      # --- CONFIGURACIÓN DEL SERVICIO ---
      # Si dices que el 4321 siempre te ha funcionado, lo mantenemos:
      - "traefik.http.services.savia-landing.loadbalancer.server.port=4321"
      - "traefik.docker.network=savia_proxy"

  # ==========================================
  # BACKEND
  # ==========================================
  ms-database-analysis:
    build:
      context: ../ms-database-analysis    # <--- El "universo" ahora es toda la carpeta del microservicio
      dockerfile: deployment/Dockerfile  # <--- Dónde está el manual de instrucciones
    container_name: ms_database_analysis
    restart: always
    environment:
      - LOGGING_LEVEL_SECURITY=INFO
      - LOGGING_LEVEL_SERVER=INFO
      - SERVER_PORT=8081
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_JPA_SHOW_LOGS=true
      - SECURITY_JWT_SECRET=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
      - SECURITY_JWT_EXPIRATION=432000000
      - FILE_PATH_REPORT_GENERATED=/app/reports/
      - FILE_PATH_DICTIONARY=/app/dictionaries/
      - JAVA_OPTS=-Xmx1024M -Xms512M
    labels:
      - "traefik.enable=true"
      # Regla para capturar el tráfico
      - "traefik.http.routers.ms-database-analysis.rule=Host(`check.saviaservicios.com`) && PathPrefix(`/ms-database-analysis`)"
      - "traefik.http.routers.ms-database-analysis.entrypoints=web"
      
      # ASIGNACIÓN DEL MIDDLEWARE (Asegúrate que el nombre coincida abajo)
      - "traefik.http.routers.ms-database-analysis.middlewares=ms-strip-prefix"
      
      # DEFINICIÓN DEL MIDDLEWARE (Aquí estaba el fallo de Traefik)
      - "traefik.http.middlewares.ms-strip-prefix.stripprefix.prefixes=/ms-database-analysis"
      
      # Configuración del servicio
      - "traefik.http.services.ms-database-analysis.loadbalancer.server.port=8081"
      - "traefik.docker.network=savia_proxy"
    volumes:
      # Formato: RUTA_HOST:RUTA_CONTENEDOR
      - /opt/savia_check/testfiles/reports/:/app/reports/
      - /opt/savia_check/astro_vs_spring/dictionaries/:/app/dictionaries/
    networks:
      - savia_internal
      - savia_proxy # Para recibir peticiones desde internet


networks:
  savia_proxy:
    external: true
  savia_internal:
    external: true
