version: '3.8'

services:
  # ==========================================
  # FRONTEND 
  # ==========================================

  # 1. Landing Page Principal
  front-savia-check:
    build:
      context: ../front/project-a  # <--- Apuntamos directo a la carpeta del proyecto
      dockerfile: ../dockerfile     # <--- El dockerfile está un nivel arriba
    container_name: savia_front_check
    restart: always
    networks:
      - savia_proxy
      - savia_internal
    labels:
      - "traefik.enable=true"
      # Router para el puerto 81 (HTTP plano)
      - "traefik.http.routers.savia-landing.rule=Host(`check.saviaservicios.com`)"
      - "traefik.http.routers.savia-landing.entrypoints=web,websecure" # <--- Esto habilita el puerto 81
      - "traefik.http.routers.savia-landing.priority=10"
      
      # Activamos TLS para el puerto 8080
      - "traefik.http.routers.savia-landing.tls=true"
      
      # Puerto de astro (confirmamos que es el 3000)
      - "traefik.http.services.savia-landing.loadbalancer.server.port=4321"

  # ==========================================
  # BACKEND
  # ==========================================
  ms-database-analysis:
    build:
      context: ../ms-database-analysis    # <--- El "universo" ahora es toda la carpeta del microservicio
      dockerfile: deployment/Dockerfile  # <--- Dónde está el manual de instrucciones
    container_name: ms_database_analysis
    restart: always
    environment:
      - LOGGING_LEVEL_SECURITY=INFO
      - LOGGING_LEVEL_SERVER=INFO
      - SERVER_PORT=8081
      - SPRING_PROFILES_ACTIVE=local
      - SPRING_JPA_SHOW_LOGS=true
      - SECURITY_JWT_SECRET=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
      - SECURITY_JWT_EXPIRATION=432000000
      - FILE_PATH_REPORT_GENERATED="/opt/astro_vs_spring/testfiles/reports/"
      - FILE_PATH_DICTIONARY="/opt/astro_vs_spring/testfiles/dictionaries/"
      - JAVA_OPTS=-Xmx1024M -Xms512M
    labels:
      - "traefik.enable=true"
      # AGREGAMOS BACKTICKS Y LA IP (por si el proxy de la empresa no manda el nombre del dominio)
      - "traefik.http.routers.ms-database-analysis.rule=Host(`check.saviaservicios.com`, `190.159.37.187`) && PathPrefix(`/ms-database-analysis`)"
      
      # HABILITAMOS AMBOS ENTRYPOINTS (Para que funcione por el 81 y el 8080)
      - "traefik.http.routers.ms-database-analysis.entrypoints=web,websecure"
      
      - "traefik.http.routers.ms-database-analysis.middlewares=ms-strip"
      - "traefik.http.middlewares.ms-strip.stripprefix.prefixes=/ms-database-analysis"
      - "traefik.http.services.ms-database-analysis.loadbalancer.server.port=8081"
    networks:
      - savia_internal
      - savia_proxy # Para recibir peticiones desde internet


networks:
  savia_proxy:
    external: true
  savia_internal:
    external: true
