version: '3.8'

services:
  traefik:
    image: traefik:v3.6.10
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # REDIRECCIÓN GLOBAL (Activada de nuevo, pero limpia)
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      # CAMBIO CLAVE: Usar puerto 443 para validar (TLS-ALPN)
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=tebanvelez91@gmail.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--log.level=INFO"
    environment:
      - DOCKER_API_VERSION=1.41  # <--- Agrega esta línea
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - proxy-net

networks:
  proxy-net: # Red pública para Traefik
    #external: true
    driver: bridge
    name: savia_proxy

